-- Run this in the Supabase SQL Editor to enable Chat

-- 1. Create the messages table
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  user_id uuid references auth.users not null,
  email text not null
);

-- 2. Turn on Security
alter table messages enable row level security;

-- 3. Allow everyone to SEE messages
create policy "Everyone can see messages"
  on messages for select
  using ( true );

-- 4. Allow logged-in users to SEND messages (if their ID matches)
create policy "Users can send messages"
  on messages for insert
  with check ( auth.uid() = user_id );

-- 5. Enable Realtime for this table
alter publication supabase_realtime add table messages;
